# This rule is not used by the project monitor-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over monitoring.cillian.website.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: monitor-operator
    app.kubernetes.io/managed-by: kustomize
  name: monitorstack-admin-role
rules:
- apiGroups:
  - monitoring.cillian.website
  resources:
  - monitorstacks
  verbs:
  - '*'
- apiGroups:
  - monitoring.cillian.website
  resources:
  - monitorstacks/status
  verbs:
  - get
